<?php
// $Id$
/**
 * @file
 * Link to configure module, and reference FL3 dependency.
 */

/**
 * Implementation of hook_install().
 */
function freelinking_install() {
  drupal_set_message(st('Configure <em>Freelinking Casetracker</em> at !url',
    array('!url' => l(st('admin/settings/freelinking'), 'admin/settings/freelinking'))));
  drupal_set_message(st('Freelinking Casetracker is for use with !module and newer.',
    array('!module' => '<em>Freelinking-6.x-3.0-alpha3</em>')));
}